#!/bin/bash
# Tyaprover Deployment Script for toowired.win
# Generated by Copilot

set -euo pipefail

echo "🚀 Deploying Tyaprover to toowired.win"
echo "======================================"

# Load configuration
source ./deploy-config.env

# Check prerequisites
check_prerequisites() {
    echo "🔍 Checking prerequisites..."

    # Check Docker
    if ! command -v docker &> /dev/null; then
        echo "❌ Docker not found. Installing..."
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
        echo "✅ Docker installed. Please log out and back in."
        exit 1
    fi

    # Check Docker Compose
    if ! command -v docker-compose &> /dev/null; then
        echo "❌ Docker Compose not found. Installing..."
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    fi

    # Check domain resolution
    echo "🌐 Checking domain resolution..."
    if ! nslookup $DOMAIN &> /dev/null; then
        echo "⚠️ Domain $DOMAIN may not be properly configured"
    fi

    echo "✅ Prerequisites checked"
}

# Deploy CapRover
deploy_caprover() {
    echo "📦 Deploying CapRover..."

    # Pull the latest image
    docker pull caprover/caprover:$CAPTAIN_VERSION

    # Run CapRover
    docker run -t --name captain-captain \
        -p 80:80 -p 443:443 -p 3000:3000 \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /captain:/captain \
        -e ACCEPTED_TERMS=true \
        -e CAPTAIN_ROOT_DOMAIN=$CAPTAIN_ROOT_DOMAIN \
        -e CAPTAIN_IS_DEBUG=false \
        caprover/caprover:$CAPTAIN_VERSION

    echo "✅ CapRover container started"
}

# Configure SSL and Domain
configure_domain() {
    echo "🔒 Configuring domain and SSL..."

    # Wait for CapRover to be ready
    echo "⏳ Waiting for CapRover to initialize..."
    sleep 30

    # Install CapRover CLI if not present
    if ! command -v caprover &> /dev/null; then
        echo "📥 Installing CapRover CLI..."
        npm install -g caprover
    fi

    # Setup CapRover
    echo "⚙️ Setting up CapRover..."
    caprover setup

    echo "✅ Domain and SSL configured"
}

# Deploy MCP Server
deploy_mcp_server() {
    echo "🤖 Deploying MCP Server..."

    cd mcp-server

    # Install dependencies
    npm install

    # Build the server
    npm run build

    # Create systemd service for MCP server
    sudo tee /etc/systemd/system/tyaprover-mcp.service > /dev/null <<EOF
[Unit]
Description=Tyaprover MCP Server
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=/home/toowired/ACTIVE/Tyaprover/mcp-server
Environment=TYAPROVER_API_URL=$TYAPROVER_API_URL
Environment=TYAPROVER_NAMESPACE=$TYAPROVER_NAMESPACE
ExecStart=/usr/bin/node build/index.js
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    # Enable and start the service
    sudo systemctl daemon-reload
    sudo systemctl enable tyaprover-mcp.service

    echo "✅ MCP Server configured"

    cd ..
}

# Setup monitoring
setup_monitoring() {
    echo "📊 Setting up monitoring..."

    # Deploy NetData via CapRover
    caprover deploy --appName netdata --imageName netdata/netdata:latest

    echo "✅ Monitoring setup complete"
}

# Create backup system
setup_backup() {
    echo "💾 Setting up backup system..."

    # Create backup script
    cat > /home/toowired/tyaprover-backup.sh << 'EOF'
#!/bin/bash
# Tyaprover Backup Script
# Generated by Copilot

BACKUP_DIR="/home/toowired/backups/tyaprover/$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"

# Backup captain data
docker run --rm -v /captain:/captain -v "$BACKUP_DIR":/backup alpine:latest \
    tar czf /backup/captain-data.tar.gz -C /captain .

# Backup Docker volumes
docker run --rm -v /var/lib/docker/volumes:/volumes -v "$BACKUP_DIR":/backup alpine:latest \
    tar czf /backup/docker-volumes.tar.gz -C /volumes .

echo "Backup completed: $BACKUP_DIR"
EOF

    chmod +x /home/toowired/tyaprover-backup.sh

    # Add to cron
    (crontab -l 2>/dev/null; echo "$BACKUP_SCHEDULE /home/toowired/tyaprover-backup.sh") | crontab -

    echo "✅ Backup system configured"
}

# Main deployment flow
main() {
    echo "🎯 Starting Tyaprover deployment process..."

    check_prerequisites
    deploy_caprover
    configure_domain
    deploy_mcp_server
    setup_monitoring
    setup_backup

    echo ""
    echo "🎉 Tyaprover deployment completed!"
    echo "=====================================+"
    echo "📍 Access your CapRover at: https://$CAPTAIN_ROOT_DOMAIN"
    echo "🔑 Default password: $CAPTAIN_PASSWORD"
    echo "📊 NetData monitoring will be available after deployment"
    echo "🤖 MCP Server configured for Claude integration"
    echo ""
    echo "📚 Next steps:"
    echo "1. Login to CapRover web interface"
    echo "2. Configure your apps"
    echo "3. Set up Claude MCP integration"
    echo "4. Test the deployment"
    echo ""
    echo "Generated by Copilot"
}

# Run main function
main "$@"
