const TyaproverMCPServer = require('./index');

describe('TyaproverMCPServer', () => {
    let server;

    beforeEach(() => {
        server = new TyaproverMCPServer.TyaproverMCPServer();
    });

    test('should create server instance', () => {
        expect(server).toBeDefined();
        expect(server.server).toBeDefined();
    });

    test('should have logging methods', () => {
        expect(typeof server.log).toBe('function');
        expect(typeof server.shouldLog).toBe('function');
    });

    test('should determine log levels correctly', () => {
        expect(server.shouldLog('error')).toBe(true);
        expect(server.shouldLog('info')).toBe(true);
    });

    test('should have makeAPICall method', () => {
        expect(typeof server.makeAPICall).toBe('function');
    });
});

// Generated by Copilot
