#!/bin/bash

# Tyaprover MCP Server Startup Script
# Generated by Copilot

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Starting Tyaprover MCP Server...${NC}"

# Check if .env file exists
if [ ! -f .env ]; then
    echo -e "${YELLOW}Warning: .env file not found. Using environment variables or defaults.${NC}"
    if [ ! -f .env.example ]; then
        echo -e "${RED}Error: .env.example file not found. Please create configuration.${NC}"
        exit 1
    else
        echo -e "${YELLOW}Hint: Copy .env.example to .env and configure your settings:${NC}"
        echo "cp .env.example .env"
    fi
fi

# Check if node_modules exists
if [ ! -d node_modules ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# Check if required environment variables are set
if [ -z "$TYAPROVER_AUTH_TOKEN" ] && [ -f .env ]; then
    source .env
fi

if [ -z "$TYAPROVER_AUTH_TOKEN" ]; then
    echo -e "${YELLOW}Warning: TYAPROVER_AUTH_TOKEN not set. API calls may fail.${NC}"
fi

# Start the server
echo -e "${GREEN}Starting server...${NC}"
exec node index.js
